apiVersion: v1  
kind: Namespace 
metadata:
  name: roboshop
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-admin 
roles:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"] # Actions on resources, create, read, update, delete 
  # Remember this only roboshop level not cluster level access
---
